pubref/rules_protobuf

README.md, bzl/cpp/README.md, bzl/go/README.md, bzl/grpc_gateway/README.md, bzl/java/README.md, bzl/javanano/README.md
Several of the README files referenced `protobuf_dependencies` as the
workspace function to fetch GRPC dependencies. It's actually called
`protobuf_repositories`.
=> Correct reference to "protobuf_dependencies"

WORKSPACE, cpp/BUILD, cpp/deps.bzl, cpp/rules.bzl, examples/wkt/go/BUILD, grpc_gateway/BUILD, protobuf/internal/proto_compile.bzl
- Removes external nanopb dependency, use the one from grpc/third party instead (fixes #7).
- Propogate inputs better to make visible with linux sandbox.
- Require grpc++ reflection API as compile dependency.
- Require well_known_protos for grpc_gateway to make visible by sandbox.
- Updates grpc/grpc to version with grpc++/ext protobuf regenerated.
- Updates rules_dotnet to avoid cfg warnings.
=> Address sandbox issues on linux

examples/helloworld/python/BUILD, examples/helloworld/python/greeter_client.py
=> Clarifies the use of greeter_client.py with grpc.

protobuf/build_file/com_github_madler_zlib.BUILD
Without the includes clause grpc fails to build, as zlib is included as <zlib.h> and not "zlib.h"
=> zlib must use -isystem

protobuf/README.md
I changed the document according to the code.
See https://github.com/pubref/rules_protobuf/blob/3f9bd0639f5692859b3effca57353d7e95638b47/protobuf/internal/proto_compile.bzl#L556
P.S. Thank you for you repo =)
=> The 'proto_compile' option 'deps' was described as 'proto_deps'. Fixed.

examples/helloworld/java/org/pubref/rules_protobuf/examples/helloworld/client/BUILD, examples/helloworld/java/org/pubref/rules_protobuf/examples/helloworld/server/BUILD, java/README.md, java/rules.bzl
This makes it easier on users to not have to remember to import //java:grpc_compiletime_deps on their own.
=> automatically export //java:grpc_compiletime_deps when with_Grpc = true

examples/extra_args/BUILD, examples/extra_args/person.proto, protobuf/README.md, protobuf/internal/proto_compile.bzl
* Also makes the `langs` attribute non-mandatory.
Closes #57
=> Adds `args` string_list option to proto_compile

examples/helloworld/grpc_gateway/BUILD, grpc_gateway/README.md, grpc_gateway/deps.bzl, grpc_gateway/rules.bzl, protobuf/internal/proto_compile.bzl
1. Adds support for the new `-request_context` option to `grpc_gateway_proto_library`,
2. Updates grpc_gateway to 686368427ddb9a51628d63db6c74fbc96a206e1f.
3. Fixes a larger bug in propagation of all grpc_gateway options.
@AmandaCameron @achew22 PTAL, specifically: should the default behavior be `request_context=True`?  Given that I figure most people considering rules_protobuf with grpc_gateway will be using a recent version of go, I opted to make this the default.
FIxes #60
=> Adds -request_context option to grpc_gateway_library

grpc_gateway/README.md
Resolves: 
```
'@org_pubref_rules_protobuf//go:rules.bzl' does not contain symbol 'grpc_gateway_proto_library'.
```
```
'@org_pubref_rules_protobuf//go:rules.bzl' does not contain symbol 'grpc_gateway_proto_compile'.
```
=> Update grpc_gateway_proto_library README to use correct load path

closure/BUILD, cpp/BUILD, csharp/BUILD, examples/extra_args/BUILD, examples/helloworld/python/BUILD, examples/wkt/go/BUILD, grpc_gateway/BUILD, java/BUILD, node/BUILD, objc/BUILD, python/BUILD, ruby/BUILD, tests/external_proto_library/BUILD, tests/with_grpc_false/BUILD
Applied https://github.com/bazelbuild/buildifier to all BUILD files.
Please, feel free to close if that is something not immediately useful. 
Just noticed it being used https://github.com/eclipse/jgit/commit/dd5e500a57fce994331dd9c9a03cb9577998a4a8
=> Re-format Bazel build files \w buildifier

.gitignore, README.md, java/README.md, protobuf/internal/proto_compile.bzl, tests/external_proto_library/.gitignore
Just fixing some typos I found as I was reading through the code and added .gitignore entries for the bazel generated build links.
=> Fix some typos in comments and add .gitignore files for bazel links

grpc_gateway/README.md
`with_grpc` in these examples is likely the cause of issues #65 and #86 since this property is not a valid property for these rules.
=> Update grpc_gateway docs

grpc_gateway/BUILD, grpc_gateway/deps.bzl, grpc_gateway/rules.bzl
* Adds new dependency on org_golang_go_genproto for pre-compiled google/api protos.
* Adds new dependency on a stripped copy of grpc_gateway for the actual google/api source protos.
Fixes #77
=> Advance grpc_gateway support to 1.2

gogo/rules.bzl
This change fixes the language labels used for the `gogofast_proto_compile`, `gogofaster_proto_compile`, and `gogoslick_proto_compile` targets. Currently attempting to use them results in the error `no such package '@org_pubref_rules_protobuf//gogofast'`.
=> Fix language labels for gogo{fast,faster,slick}_proto_compile

objc/BUILD
Obj-C protocol buffers with underscores in the filename cannot be build because bazel looks for the wrong output file. Setting the output_file_style to "pascal" fixes this.
For example: the proto some_thing.proto is compiled to SomeThing.pbobjc.h which is what bazel expects. I tested it with bazel v0.5.1.
=> Use pascal file style for objc protos

go/deps.bzl
For your convenience, the relevant commit list is
https://github.com/golang/protobuf/commits/master
I would like this since it would make it possible for me to link
against a modern timestamp.proto.
I changed the hash to the most recent change, but the change
that is most important to me is
github.com/golang/protobuf/commit/157d9c53be5810dd5a0fac4a467f7d5f400042ea
> regenerate pb.go files with protobuf 3.3.0
It would also be nice to have
github.com/golang/protobuf/commit/5a0f697c9ed9d68fef0116532c6e05cfeae00e55
> Deserialize JSON NaN, Infinity and -Infinity to corresponding Go values
----
The problem I'm trying to address is
```sh
ERROR: /ELIDED/BUILD:57:1: null failed: Process exited with status 1 [sandboxed].
bazel-out/darwin_x86_64-fastbuild/genfiles/api/common.pb.go:79: …
```
=> Update dependency on github/golang/protobuf to latest.

grpc_gateway/deps.bzl
It's unclear to me if this is a transient issue or not, but this addressed timeouts I was seeing.
=> Use https instead of http for grpc gateway archive.

protobuf/internal/proto_compile.bzl, tests/generated_proto_file/BUILD, tests/generated_proto_file/simple.proto
This PR is an attempt to deal with issues related to generating *_proto_libraries from proto files that were also generated as part of a bazel build.
When calculating protobuf_out and grpc_out, this PR adds logic that compares the path of the first proto being compiled to the bazel GENDIR. If the path startswith the GENDIR, this PR sets the outdir to ".".
An example "test" is also included to exercise this logic (for cpp and go proto libs).
Fixes: #116
=> Add support for using generated protos w/o output_to_workspace

WORKSPACE, examples/helloworld/python/BUILD
This renames `package` to `requirement` to avoid a conflict with a Bazel built-in function.
=> Update rules_python to avoid builtin conflict.

protobuf/internal/proto_compile.bzl
This PR is the companion PR to #118 .  It probably should have been part of that PR.
The issue:
When generating code from generated proto files, output path calculation can lead to incorrect results. This manifests as error messages indicating that the expected output file has not been generated. Example error:
> ERROR: .../BUILD:7:1: output 'local-fastbuild/genfiles/go_default_library_tmpl.pb.go' was not created.
ERROR: .../BUILD:7:1: not all outputs were created or valid. 
This PR edits the calculated output path in `_build_output_files`. When the calculated relative dirname for the output path ends with `ctx.var["GENDIR"]`, this change sets the path to `[]`. This should ensure that files generated from generated files are not placed in nested GENDIRs.
Same BUILD run with this change:
> …
=> Update output path calculation for generated protos

protobuf/internal/proto_compile.bzl
cc: @guptasu (who has been my partner in crime in an evolving use case for these updates).
In the prior PR (https://github.com/pubref/rules_protobuf/pull/128), we updated the calculated path to be `[]` when the relative dir was *exactly* `ctx.var["GENDIR"]`. This achieves the desired effect when dealing with generated protos at the *root* of genfiles.
However, in cases when the generated proto is in subdirectories of genfiles (like in the case of external protos in cross-repo scenarios), this is not sufficient.
This PR solves this issue by searching for the final part of the `ctx.var["GENDIR"]` in `path`. If found, it sets the path to '[]' as before.
Python is NOT my strong suit, so there might be a more eloquent expression of the goal, but this seems to work in testing.
If there is a …
=> Update genfiles path calculation logic

DEPENDENCIES.md, protobuf/deps.bzl
Using a different SHA than the upstream 3.4.0 tag causes dependency problems
in larger projects that already have com_google_protobuf v3.4.0 in their WORKSPACE.
=> Align Protobuf dependency with upstream 3.4.0 tag

cpp/generate_cc.modified.bzl
`generate_cc.bzl` creates rules that call `protoc` with options like `--cpp_out=:some/path`.  This is the form that `protoc` expects to take, and it is usually fine.  However, on Windows, Bazel runs commands through an MSYS shell, and when executing Windows-native commands, MSYS tries to translate anything that looks POSIXy to be Windowsy.  Unfortunately, here its heuristics kick in, thinking it looks like a POSIXy colon-delimited PATH, and converts the colon to a semicolon, which is then misinterpreted by `protoc`.
When there are no options, we omit the colon, which avoids this error when building on Windows.  This still doesn't solve the case when options do need to be passed, but fortunately that case has not yet come up for us, so this is an acceptable stopgap solution.
=> Change generate_cc.bzl to avoid using colon when unnecessary

protobuf/README.md
There is a bug in the `proto_language` documentation, `prefix` is not a valid argument to the `proto_language` rule: https://github.com/pubref/rules_protobuf/blob/master/protobuf/internal/proto_language.bzl#L34
It seems like it's changed to `go_prefix` here: https://github.com/pubref/rules_protobuf/commit/0708c69ada41afbeca7b8c35a643518147471a92
=> Update proto_language Readme

.travis.yml, WORKSPACE, protobuf/internal/proto_repositories.bzl, protobuf/internal/require.bzl
Adds a check in the require function to avoid strictness
if the pre-existing rule does not have a sha value set
(where strict is defined as "fail if we try to re-load / override
an external dependency where the sha256 values for the
rule don't match").
Removes 0.5.x from travis matrix and removes residual pip
dependency.
=> Update to rules_go 0.7.0+

java/BUILD, java/deps.bzl, java/rules.bzl
Also specify the OS-sniffing `config_setting` to use `host_cpu` rather than `cpu`, as the `proto_compile` actions are specified to run in the host context.
=> Add prebuilt Java gRPC dependency for Windows

gogo/deps.bzl
This change bumps the version of gogo to include https://github.com/gogo/protobuf/pull/350, and also disables the `go_proto_library` rule generation now enabled by default in `rules_go`.
For `@gogo//gogoproto`, the generated `go_proto_library` rule contains an incorrect golang/protobuf dependency (see below). The generated `go_proto_library` rule is not necessary since gogoproto has already generated gogo.pb.go and included it in the repo.
```
external/com_github_gogo_protobuf/gogoproto/helper.go:35:37: cannot use E_Embed (type *"github.com/golang/protobuf/proto".ExtensionDesc) as type *"github.com/gogo/protobuf/proto".ExtensionDesc in argument to "github.com/gogo/protobuf/proto".GetBoolExtension
external/com_github_gogo_protobuf/gogoproto/helper.go:39:37: cannot use E_Nullable (type …
```
=> Bump gogo version and disable go_proto_library generation by rules_go

protobuf/internal/proto_compile.bzl
Fixes argument use in some Bazel-on-Windows shell configurations.
=> Replace command arguments array with formatted command string

csharp/rules.bzl, node/rules.bzl, objc/rules.bzl, python/rules.bzl, ruby/rules.bzl
This shows up when using a different version of google test to the one protobuf expects to be built with.
An alternative is to explicitly call `cpp_proto_repositories()`, passing any necessary arguments first (`overrides` in this case) and then call eg. `python_proto_repositories(omit_cpp_repositories=True)`. This is less obvious without reading the bazel rules themselves.
For reference, the error was:
```
An existing http_archive rule 'com_google_googletest' was already loaded with a sha256 value of '...'.  Refusing to overwrite this with the requested value ('f87029f647276734ef076785f76652347993b6d13ac1cbb2d2e976e16d2f8137').
Either remove the pre-existing rule from your WORKSPACE or exclude it from loading by rules_protobuf.
```
=> Allow overriding implicit cpp repositories options in other language rules

WORKSPACE, node/deps.bzl, protobuf/deps.bzl
With a recent build of bazel, the HEAD revision no longer builds:
```
~/src/github/pubref/rules_protobuf$ bazel build python
.
ERROR: /external/io_bazel_rules_dotnet/dotnet/csharp.bzl:25:10: The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false
ERROR: error loading package '': Extension 'dotnet/csharp.bzl' has errors
ERROR: error loading package '': Extension 'dotnet/csharp.bzl' has errors
INFO: Elapsed time: 1.290s
FAILED: Build did NOT complete successfully (0 packages loaded)
```
=> Fix the Python build by updating the dotnet import.

WORKSPACE
=> Fix 'Closure Rules requires Bazel >=0.4.5 but was 0.11.1'

protobuf/internal/proto_compile.bzl, tests/generated_proto_file/BUILD, tests/generated_proto_file/complicated/complicated.proto, tests/generated_proto_file/complicated/complicated_copy.proto, tests/generated_proto_file/subdir/simple.proto
Automatically update the proto_path when dealing with a mixture of generated and non-generated proto sources.
This also automatically adds external rules that you depend on to the proto_path.
=> Fix proto_path to handle generated sources

protobuf/internal/proto_compile.bzl
potential fix for https://github.com/pubref/rules_protobuf/issues/142
relative path to target file is lost if file path does not start with base.
this always occurs when building from external since external working dir ditches external prefix.
e.g.: ".../external/a/b/c.proto" with BUILD at a has base a, a != external, so we return []
Instead we ignore base and take relative path from BUILD directory to file. (not sure why not use this in the first place)
There may exist more elegant solution.
Without this fix, depending on external pb libraries built with rules_protobuf will fail without complete restructuring.
=> Fix issue 142

protobuf/internal/proto_compile.bzl
Hey, I noticed that `root` attr is defined and documented for `proto_compile` but not used in code. Let me know if this is the right way to fix it.
=> Fix root attr on proto_compile
